name: Nightly Build

on:
  push:
    branches:
      - refactor-build

jobs:
  build:
    name: Nightly Build
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: install python deps
        shell: bash
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install -r requirements.txt

      - name: build x86_64
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source venv/bin/activate
          cd projects
          make PLATFORM=X64
          gh release upload nightly lgpt.x64
